# ================================================================
# Shopify App Configuration
# After filling in your values, this file is read by the Shopify CLI
# ================================================================

name = "Rizzz Reviews"
client_id = "66759873db8683deef1e49496854ca98"
handle = "rizzz-reviews"
application_url = "shopify-node-app-rizz-4f6god817-rizzz8.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "https://test-rizzz.myshopify.com/"

[access_scopes]
scopes = "read_products,read_orders,write_script_tags,read_customers"

[auth]
redirect_urls = [
  "https://shopify-node-app-rizz-4f6god817-rizzz8.vercel.app/auth/callback",
  "https://shopify-node-app-rizz-4f6god817-rizzz8.vercel.appp/auth/callback"
]

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = ["orders/fulfilled"]
  uri = "/webhooks/orders-fulfilled"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = ["shop/redact"]
  uri = "/webhooks/shop-redact"

  [[webhooks.subscriptions]]
  topics = ["customers/redact"]
  uri = "/webhooks/customers-redact"

  [[webhooks.subscriptions]]
  topics = ["customers/data_request"]
  uri = "/webhooks/customers-data-request"

[pos]
embedded = false
