# ================================================================
# Shopify App Configuration
# After filling in your values, this file is read by the Shopify CLI
# ================================================================

name = "Rizzz Reviews"
client_id = "c96655ef1ee068e01532b48d62f16b90"
handle = "rizzz-reviews"
application_url = "https://shopify-node-app-tga6.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "https://test-rizzz.myshopify.com/"

[access_scopes]
scopes = "read_products,read_orders,write_script_tags,read_customers"

[auth]
redirect_urls = [
  "https://shopify-node-app-tga6.vercel.app/auth/callback",
]

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = ["orders/fulfilled"]
  uri = "/webhooks/orders-fulfilled"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app-uninstalled"

[pos]
embedded = false
